[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8"]

[project]
name = "cusmic"
dynamic = ["version"]
dependencies = ["cupy"]

[project.optional-dependencies]
slim = []
cli = ["click", "numpy", "astropy"]

[project.scripts]
cusmic = "cusmic.__main__:main"

[tool.setuptools.packages.find]
where = ["mod"]
